#!/bin/sh

EXAMPLE_MODE=normal
EXAMPLE_MAIN=com.rbmhtechnology.example.ordermgnt.OrderExample

while [[ $# > 1 ]]; do
    key="$1"
    case $key in
        -r|--recover)
        EXAMPLE_MODE=recover
        ;;
        -j|--java)
        EXAMPLE_MAIN=com.rbmhtechnology.example.japi.ordermgnt.OrderExample
        ;;
        *)
        # unknown option
        ;;
    esac
    shift # past argument or value
done

EXAMPLE_CONF=ordermgnt/location-$1.conf

if [[ ! -f ./example/.example-classpath ]]; then
    sbt exampleClasspath || exit 1
fi

source ./example/.example-classpath

exec java -cp "$EXAMPLE_CLASSPATH" $EXAMPLE_MAIN $EXAMPLE_CONF $EXAMPLE_MODE
