#!/bin/sh

EXAMPLE_MODE=normal
EXAMPLE_MAIN=com.rbmhtechnology.example.OrderExample

while [[ $# > 1 ]]
do
key="$1"
case $key in
    -r|--recover)
    EXAMPLE_MODE=recover
    ;;
    -j|--java)
    EXAMPLE_MAIN=com.rbmhtechnology.example.japi.OrderExample
    ;;
    *)
    # unknown option
    ;;
esac
shift # past argument or value
done

EXAMPLE_CONF=location-$1.conf

IVY_CACHE=$HOME/.ivy2/cache

java -cp \
./target/scala-2.11/test-classes:\
./target/scala-2.11/classes:\
$IVY_CACHE/com.datastax.cassandra/cassandra-driver-core/bundles/cassandra-driver-core-2.1.5.jar:\
$IVY_CACHE/com.google.guava/guava/bundles/guava-16.0.jar:\
$IVY_CACHE/com.codahale.metrics/metrics-core/bundles/metrics-core-3.0.2.jar:\
$IVY_CACHE/org.slf4j/slf4j-api/jars/slf4j-api-1.7.5.jar:\
$IVY_CACHE/com.google.protobuf/protobuf-java/bundles/protobuf-java-2.5.0.jar:\
$IVY_CACHE/com.typesafe.akka/akka-protobuf_2.11/jars/akka-protobuf_2.11-2.4.0.jar:\
$IVY_CACHE/com.typesafe.akka/akka-remote_2.11/jars/akka-remote_2.11-2.4.0.jar:\
$IVY_CACHE/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar:\
$IVY_CACHE/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.4.0.jar:\
$IVY_CACHE/com.typesafe/config/bundles/config-1.3.0.jar:\
$IVY_CACHE/io.netty/netty/bundles/netty-3.10.3.Final.jar:\
$IVY_CACHE/org.uncommons.maths/uncommons-maths/jars/uncommons-maths-1.2.2a.jar:\
$IVY_CACHE/commons-io/commons-io/jars/commons-io-2.4.jar:\
$IVY_CACHE/org.fusesource.leveldbjni/leveldbjni-all/bundles/leveldbjni-all-1.8.jar:\
$IVY_CACHE/org.scalaz/scalaz-core_2.11/bundles/scalaz-core_2.11-7.1.0.jar:\
$IVY_CACHE/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.2.jar:\
$IVY_CACHE/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.2.jar:\
$IVY_CACHE/com.typesafe.akka/akka-testkit_2.11/jars/akka-testkit_2.11-2.4.0.jar:\
$IVY_CACHE/com.typesafe.akka/akka-multi-node-testkit_2.11/jars/akka-multi-node-testkit_2.11-2.4.0.jar:\
$IVY_CACHE/org.cassandraunit/cassandra-unit/jars/cassandra-unit-2.0.2.2.jar:\
$IVY_CACHE/org.hamcrest/hamcrest-all/jars/hamcrest-all-1.1.jar:\
$IVY_CACHE/org.apache.cassandra/cassandra-all/jars/cassandra-all-2.1.0.jar:\
$IVY_CACHE/org.xerial.snappy/snappy-java/bundles/snappy-java-1.0.5.jar:\
$IVY_CACHE/net.jpountz.lz4/lz4/jars/lz4-1.2.0.jar:\
$IVY_CACHE/com.ning/compress-lzf/bundles/compress-lzf-0.8.4.jar:\
$IVY_CACHE/commons-codec/commons-codec/jars/commons-codec-1.2.jar:\
$IVY_CACHE/org.apache.commons/commons-lang3/jars/commons-lang3-3.1.jar:\
$IVY_CACHE/org.apache.commons/commons-math3/jars/commons-math3-3.2.jar:\
$IVY_CACHE/com.googlecode.concurrentlinkedhashmap/concurrentlinkedhashmap-lru/jars/concurrentlinkedhashmap-lru-1.3.jar:\
$IVY_CACHE/org.antlr/antlr/jars/antlr-3.2.jar:\
$IVY_CACHE/org.antlr/antlr-runtime/jars/antlr-runtime-3.2.jar:\
$IVY_CACHE/org.antlr/stringtemplate/jars/stringtemplate-3.2.1.jar:\
$IVY_CACHE/antlr/antlr/jars/antlr-2.7.7.jar:\
$IVY_CACHE/org.codehaus.jackson/jackson-core-asl/jars/jackson-core-asl-1.9.2.jar:\
$IVY_CACHE/org.codehaus.jackson/jackson-mapper-asl/jars/jackson-mapper-asl-1.9.2.jar:\
$IVY_CACHE/jline/jline/jars/jline-1.0.jar:\
$IVY_CACHE/com.googlecode.json-simple/json-simple/jars/json-simple-1.1.jar:\
$IVY_CACHE/com.boundary/high-scale-lib/jars/high-scale-lib-1.0.6.jar:\
$IVY_CACHE/org.yaml/snakeyaml/bundles/snakeyaml-1.11.jar:\
$IVY_CACHE/org.mindrot/jbcrypt/jars/jbcrypt-0.3m.jar:\
$IVY_CACHE/com.yammer.metrics/metrics-core/jars/metrics-core-2.2.0.jar:\
$IVY_CACHE/com.addthis.metrics/reporter-config/jars/reporter-config-2.1.0.jar:\
$IVY_CACHE/org.hibernate/hibernate-validator/jars/hibernate-validator-4.3.0.Final.jar:\
$IVY_CACHE/javax.validation/validation-api/jars/validation-api-1.0.0.GA.jar:\
$IVY_CACHE/org.jboss.logging/jboss-logging/jars/jboss-logging-3.1.0.CR2.jar:\
$IVY_CACHE/com.thinkaurelius.thrift/thrift-server/jars/thrift-server-0.3.5.jar:\
$IVY_CACHE/com.lmax/disruptor/jars/disruptor-3.0.1.jar:\
$IVY_CACHE/org.apache.thrift/libthrift/jars/libthrift-0.9.1.jar:\
$IVY_CACHE/org.apache.httpcomponents/httpclient/jars/httpclient-4.2.5.jar:\
$IVY_CACHE/org.apache.httpcomponents/httpcore/jars/httpcore-4.2.4.jar:\
$IVY_CACHE/junit/junit/jars/junit-4.6.jar:\
$IVY_CACHE/com.clearspring.analytics/stream/jars/stream-2.5.2.jar:\
$IVY_CACHE/it.unimi.dsi/fastutil/jars/fastutil-6.5.7.jar:\
$IVY_CACHE/net.sf.supercsv/super-csv/jars/super-csv-2.1.0.jar:\
$IVY_CACHE/org.apache.cassandra/cassandra-thrift/jars/cassandra-thrift-2.1.0.jar:\
$IVY_CACHE/net.java.dev.jna/jna/jars/jna-4.0.0.jar:\
$IVY_CACHE/com.github.jbellis/jamm/jars/jamm-0.2.6.jar:\
$IVY_CACHE/io.netty/netty-all/jars/netty-all-4.0.20.Final.jar:\
$IVY_CACHE/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.6.1.jar:\
$IVY_CACHE/log4j/log4j/bundles/log4j-1.2.16.jar:\
$IVY_CACHE/com.sun.xml.bind/jaxb-impl/jars/jaxb-impl-2.2.4-1.jar:\
$IVY_CACHE/javax.xml.bind/jaxb-api/jars/jaxb-api-2.2.3.jar:\
$IVY_CACHE/javax.xml.stream/stax-api/jars/stax-api-1.0-2.jar:\
$IVY_CACHE/javax.activation/activation/jars/activation-1.1.jar:\
$IVY_CACHE/org.hectorclient/hector-core/bundles/hector-core-1.1-4.jar:\
$IVY_CACHE/commons-pool/commons-pool/jars/commons-pool-1.5.3.jar:\
$IVY_CACHE/com.github.stephenc.eaio-uuid/uuid/jars/uuid-3.2.0.jar:\
$IVY_CACHE/com.ecyrd.speed4j/speed4j/jars/speed4j-0.9.jar:\
$IVY_CACHE/commons-lang/commons-lang/jars/commons-lang-2.6.jar:\
$IVY_CACHE/commons-cli/commons-cli/jars/commons-cli-1.2.jar:\
$IVY_CACHE/org.functionaljava/functionaljava/jars/functionaljava-4.2-beta-1.jar:\
$IVY_CACHE/org.functionaljava/functionaljava-java8/jars/functionaljava-java8-4.2-beta-1.jar:\
$IVY_CACHE/org.scalatest/scalatest_2.11/jars/scalatest_2.11-2.1.4.jar:\
$IVY_CACHE/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.0.jar \
$EXAMPLE_MAIN $EXAMPLE_CONF $EXAMPLE_MODE

# ------------------------------------------------------------------
# Alternative: use this if dependencies should be obtained from sbt
# ------------------------------------------------------------------
#sbt "test:runMain $EXAMPLE_MAIN $EXAMPLE_CONF $EXAMPLE_MODE"
