/*
 * Copyright (C) 2015 Red Bull Media House GmbH <http://www.redbullmediahouse.com> - all rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.rbmhtechnology.eventuate

import java.util.concurrent.TimeUnit
import java.util.function.{Function => JFunction}

import akka.actor._

import scala.collection.JavaConverters._
import scala.concurrent.duration._

import ReplicationProtocol._

private object ReplicationSettings {
  def apply(system: ActorSystem): ReplicationSettings =
    new ReplicationSettings(system)
}

private class ReplicationSettings(system: ActorSystem) {
  val config = system.settings.config.getConfig("eventuate.log.replication")

  val replicationRetryInterval: FiniteDuration =
    config.getDuration("retry-interval", TimeUnit.MILLISECONDS).millis

  val replicationBatchSize: Int =
    config.getInt("batch-size-max")

  val failureDetectionLimit =
    config.getDuration("failure-detection-limit", TimeUnit.MILLISECONDS).millis
}

object ReplicationEndpoint {
  /**
   * Default log name.
   */
  val DefaultLogName: String = "default"

  /**
   * Published to the actor system's event stream if a remote log is available.
   */
  case class Available(endpointId: String, logName: String)

  /**
   * Published to the actor system's event stream if a remote log is unavailable.
   */
  case class Unavailable(endpointId: String, logName: String)

  /**
   * Matches a string of format "<hostname>:<port>".
   */
  private object Address {
    def unapply(s: String): Option[(String, Int)] = {
      val hp = s.split(":")
      Some((hp(0), hp(1).toInt))
    }
  }

  /**
   * Creates a [[ReplicationEndpoint]] with a single event log with name [[DefaultLogName]]. The
   * replication endpoint id and replication connections must be configured as follows in `application.conf`:
   *
   * {{{
   *   endpoint.id = "endpoint-id"
   *   endpoint.connections = ["host-1:port-1", "host-2:port-2", ..., "host-n:port-n"]
   * }}}
   *
   * @param logFactory Factory of log actor `Props`. The `String` parameter of the factory is a unique
   *                   log id generated by this endpoint. The log actor must be assigned this log id.
   */
  def apply(logFactory: String => Props)(implicit system: ActorSystem): ReplicationEndpoint = {
    val config = system.settings.config
    val connections = config.getStringList("eventuate.endpoint.connections").asScala.toSet[String].map {
      case Address(host, port) => ReplicationConnection(host, port)
    }
    apply(logFactory, connections)
  }

  /**
   * Creates a [[ReplicationEndpoint]] with a single event log with name [[DefaultLogName]]. The
   * replication endpoint id must be configured as follows in `application.conf`:
   *
   * {{{
   *   endpoint.id = "endpoint-id"
   * }}}
   *
   * @param logFactory Factory of log actor `Props`. The `String` parameter of the factory is a unique
   *                   log id generated by this endpoint. The log actor must be assigned this log id.
   * @param connections Replication connections to other replication endpoints.
   */
  def apply(logFactory: String => Props, connections: Set[ReplicationConnection])(implicit system: ActorSystem): ReplicationEndpoint = {
    val config = system.settings.config
    val endpointId = config.getString("eventuate.endpoint.id")
    new ReplicationEndpoint(endpointId, Set(ReplicationEndpoint.DefaultLogName), logFactory, connections)(system)
  }

  /**
   * Java API.
   *
   * Creates a [[ReplicationEndpoint]] with a single event log with name [[DefaultLogName]]. The
   * replication endpoint id and replication connections must be configured as follows in `application.conf`:
   *
   * {{{
   *   endpoint.id = "endpoint-id"
   *   endpoint.connections = ["host-1:port-1", "host-2:port-2", ..., "host-n:port-n"]
   * }}}
   *
   * @param logFactory Factory of log actor `Props`. The `String` parameter of the factory is a unique
   *                   log id generated by this endpoint. The log actor must be assigned this log id.
   */
  def create(logFactory: JFunction[String, Props], system: ActorSystem) =
    apply(id => logFactory.apply(id))(system)
}

/**
 * A replication endpoint connects to other replication endpoints for replicating events. Events are
 * replicated from the connected endpoints to this endpoint. The connected endpoints are ''replication
 * sources'', this endpoint is a ''replication target''. To setup bi-directional replication, the other
 * replication endpoints must additionally setup replication connections to this endpoint.
 *
 * A replication endpoint manages one or more event logs. Event logs are indexed by name. Events are
 * replicated only between event logs with matching names.
 *
 * @param id Unique replication endpoint id.
 * @param logNames Names of the event logs managed by this replication endpoint.
 * @param logFactory Factory of log actor `Props`. The `String` parameter of the factory is a unique
 *                   log id generated by this endpoint. The log actor must be assigned this log id.
 * @param connections Replication connections to other replication endpoints.
 */
class ReplicationEndpoint(val id: String, val logNames: Set[String], logFactory: String => Props, connections: Set[ReplicationConnection])(implicit system: ActorSystem) { endpoint =>
  /**
   * This replication endpoint's info object.
   */
  private val info: ReplicationEndpointInfo =
    ReplicationEndpointInfo(id, logNames)

  /**
   * The log actors managed by this endpoint, indexed by their name.
   */
  val logs: Map[String, ActorRef] =
    logNames.map(logName => logName -> system.actorOf(logFactory(logId(logName)), name = logId(logName))).toMap

  /**
   * Returns the unique log id for given `logName`.
   */
  def logId(logName: String): String =
    info.logId(logName)

  system.actorOf(Props(new SourceReplicationConnector(info)), name = SourceReplicationConnector.Name)
  system.actorOf(Props(new NotificationChannel), name = NotificationChannel.Name)

  connections.map { connection =>
    system.actorOf(Props(new TargetReplicationConnector(endpoint, connection)))
  }
}

/**
 * References a remote replication source.
 */
private case class ReplicationSource(
  endpointId: String,
  logName: String,
  logId: String,
  log: ActorSelection)

/**
 * References a local replication target.
 */
private case class ReplicationTarget(
  endpointId: String,
  logName: String,
  logId: String,
  log: ActorRef)

private object SourceReplicationConnector {
  val Name = "connector"
}

/**
 * Replication connector at a source [[ReplicationEndpoint]].
 */
private class SourceReplicationConnector(sourceEndpointInfo: ReplicationEndpointInfo) extends Actor {
  def receive = {
    case GetReplicationEndpointInfo =>
      sender() ! GetReplicationEndpointInfoSuccess(sourceEndpointInfo)
  }
}

/**
 * Replication connector at a target [[ReplicationEndpoint]]. Obtains a [[ReplicationEndpointInfo]]
 * object from a source replication endpoint for settings up log [[Replicator]]s, one per common log
 * name.
 */
private class TargetReplicationConnector(targetEndpoint: ReplicationEndpoint, connection: ReplicationConnection) extends Actor {
  import context.dispatcher

  private val connector = selection(SourceReplicationConnector.Name)
  private val schedule = context.system.scheduler.schedule(0.seconds, ReplicationSettings(context.system).replicationRetryInterval, new Runnable {
    override def run() = connector ! GetReplicationEndpointInfo
  })

  private var connected = false

  def receive = {
    case GetReplicationEndpointInfoSuccess(info) if !connected =>
      info.logNames.intersect(targetEndpoint.logNames).foreach { logName =>
        val sourceLogId = info.logId(logName)
        val source = ReplicationSource(info.endpointId, logName, sourceLogId, selection(sourceLogId))
        val target = ReplicationTarget(targetEndpoint.id, logName, targetEndpoint.logId(logName), targetEndpoint.logs(logName))
        context.actorOf(Props(new Replicator(source, target, connection.filters.get(logName), selection(NotificationChannel.Name))))
      }
      connected = true
      schedule.cancel()
  }

  private def selection(actor: String): ActorSelection = {
    import connection._

    val protocol = context.system match {
      case sys: ExtendedActorSystem => sys.provider.getDefaultAddress.protocol
      case sys                      => "akka.tcp"
    }

    context.actorSelection(s"${protocol}://${name}@${host}:${port}/user/${actor}")
  }

  override def postStop(): Unit =
    schedule.cancel()
}

/**
 * Replicates events from a source log to a target log.
 */
private class Replicator(source: ReplicationSource, target: ReplicationTarget, filter: Option[ReplicationFilter], notificationChannel: ActorSelection) extends Actor {
  import ReplicationServerFailureDetector._
  import context.dispatcher

  val replicationSettings = ReplicationSettings(context.system)
  val replicationFilter = filter match {
    case Some(f) => SourceLogIdExclusionFilter(target.logId).and(f)
    case None    => SourceLogIdExclusionFilter(target.logId)
  }

  val failureDetector = context.actorOf(Props(new ReplicationServerFailureDetector(source.endpointId, source.logName)))
  val registrationSchedule = context.system.scheduler.schedule(0.seconds, replicationSettings.replicationRetryInterval, new Runnable {
    override def run() = notificationChannel ! SubscribeReplicator(target.logId, self, replicationFilter)
  })

  var correlationId = 0

  val idle: Receive = {
    case ReplicationDue =>
      val correlationId = nextCorrelationId()
      target.log ! GetLastSourceLogReadPosition(source.logId, correlationId)
      context.become(replicating(correlationId))
      failureDetector ! Tick
    case ReceiveTimeout =>
      val correlationId = nextCorrelationId()
      target.log ! GetLastSourceLogReadPosition(source.logId, correlationId)
      context.become(replicating(correlationId))
  }

  def replicating(correlationId: Int): Receive = {
    case GetLastSourceLogReadPositionSuccess(sourceLogId, lastSourceLogSequenceNrStored, `correlationId`) =>
      source.log ! ReplicationRead(lastSourceLogSequenceNrStored + 1, replicationSettings.replicationBatchSize, replicationFilter, target.logId, correlationId)
    case GetLastSourceLogReadPositionFailure(cause, `correlationId`) =>
      // TODO: log cause
      context.become(idle)
    case ReplicationReadSuccess(events, lastSourceLogSequenceNrRead, _, `correlationId`) =>
      target.log ! ReplicationWrite(events, source.logId, lastSourceLogSequenceNrRead, correlationId)
      failureDetector ! Tick
    case ReplicationReadFailure(cause, _, `correlationId`) =>
      // TODO: log cause
      context.become(idle)
      failureDetector ! Tick
    case ReplicationWriteSuccess(num, lastSourceLogSequenceNrStored, `correlationId`) if num > 0 =>
      val correlationId = nextCorrelationId()
      source.log ! ReplicationRead(lastSourceLogSequenceNrStored + 1, replicationSettings.replicationBatchSize, replicationFilter, target.logId, correlationId)
      context.become(replicating(correlationId))
    case ReplicationWriteSuccess(_, _, `correlationId`) =>
      context.become(idle)
    case ReplicationWriteFailure(cause, `correlationId`) =>
      // TODO: log cause
      context.become(idle)
    case ReceiveTimeout =>
      context.become(idle)
  }

  def receive = idle

  override def preStart(): Unit = {
    context.setReceiveTimeout(replicationSettings.replicationRetryInterval)
    self ! ReplicationDue
  }

  override def postStop(): Unit = {
    registrationSchedule.cancel()
  }

  private def nextCorrelationId(): Int = {
    correlationId += 1
    correlationId
  }
}

private object ReplicationServerFailureDetector {
  case object Tick
}

private class ReplicationServerFailureDetector(sourceEndpointId: String, logName: String) extends Actor {
  import ReplicationServerFailureDetector._
  import ReplicationEndpoint._

  val limit = ReplicationSettings(context.system).failureDetectionLimit.toMillis
  var lastTick: Long = 0L

  context.setReceiveTimeout(limit.millis)

  def receive = {
    case Tick =>
      val currentTime = System.currentTimeMillis
      val lastInterval =  currentTime - lastTick
      if (lastInterval >= limit) {
        context.system.eventStream.publish(Available(sourceEndpointId, logName))
        lastTick = currentTime
      }
    case ReceiveTimeout =>
      context.system.eventStream.publish(Unavailable(sourceEndpointId, logName))
  }
}

private object NotificationChannel {
  val Name = "notifications"
}

/**
 * Notifies registered [[Replicator]]s about source log updates.
 */
private class NotificationChannel extends Actor {
  // targetLogId -> subscription
  var registry: Map[String, SubscribeReplicator] = Map.empty

  // targetLogIds for which a read operation is in progress
  var reading: Set[String] = Set.empty

  def receive = {
    case r @ SubscribeReplicator(targetLogId, _, _) =>
      registry += (targetLogId -> r)
    case Updated(events) =>
      registry.foreach {
        case (targetLogId, reg) => if (events.exists(reg.filter.apply)) {
          if (!reading.contains(targetLogId)) reg.replicator ! ReplicationDue
          else { /* skip sending a notification, read is in progress anyway */ }
        }
      }
    case r: ReplicationRead =>
      reading += r.targetLogId
    case r: ReplicationReadSuccess =>
      reading -= r.targetLogId
    case r: ReplicationReadFailure =>
      reading -= r.targetLogId
  }

  override def preStart(): Unit = {
    val stream = context.system.eventStream
    stream.subscribe(self, classOf[Updated])
    stream.subscribe(self, classOf[ReplicationRead])
    stream.subscribe(self, classOf[ReplicationReadSuccess])
    stream.subscribe(self, classOf[ReplicationReadFailure])
  }

  override def postStop(): Unit = {
    context.system.eventStream.unsubscribe(self)
  }
}
